export type Task = {
  id: string;
  time: string;
  description: string;
  isCritical: boolean;
  completed: boolean;
};

export type DayRoutine = {
  day: string;
  tasks: Task[];
  notes: string;
};

export const initialRoutine: DayRoutine[] = [
  {
    day: 'Monday',
    tasks: [
      { id: 'mon-0', time: '1:45–2:00 AM (Sun)', description: 'Sleep', isCritical: true, completed: false },
      { id: 'mon-1', time: '8:45', description: 'Wake up + drink water', isCritical: false, completed: false },
      { id: 'mon-2', time: '8:45–8:50', description: 'Toilet', isCritical: false, completed: false },
      { id: 'mon-3', time: '8:50–8:55', description: 'Brush', isCritical: false, completed: false },
      { id: 'mon-4', time: '8:55–9:00', description: 'Face wash', isCritical: false, completed: false },
      { id: 'mon-5', time: '9:00–9:15', description: 'Breakfast (omelette/bread/milk)', isCritical: false, completed: false },
      { id: 'mon-6', time: '9:15–9:40', description: 'Lab revision', isCritical: false, completed: false },
      { id: 'mon-7', time: '9:40–10:00', description: 'Go to lab', isCritical: false, completed: false },
      { id: 'mon-8', time: '10:00–12:00', description: 'Lab', isCritical: true, completed: false },
      { id: 'mon-9', time: '12:00–12:10', description: 'Relax', isCritical: false, completed: false },
      { id: 'mon-10', time: '12:10–12:25', description: 'Bath', isCritical: false, completed: false },
      { id: 'mon-11', time: '12:25–12:30', description: 'Get ready', isCritical: false, completed: false },
      { id: 'mon-12', time: '12:30–12:45', description: 'Lunch', isCritical: false, completed: false },
      { id: 'mon-13', time: '12:45–1:00', description: 'Sit/walk', isCritical: false, completed: false },
      { id: 'mon-14', time: '1:00–5:00', description: 'Classes', isCritical: true, completed: false },
      { id: 'mon-15', time: '5:15–5:30', description: 'Snack', isCritical: false, completed: false },
      { id: 'mon-16', time: '5:30–6:00', description: 'Rest', isCritical: false, completed: false },
      { id: 'mon-17', time: '6:00–6:20', description: 'Run + stretch', isCritical: false, completed: false },
      { id: 'mon-18', time: '6:30–7:00', description: 'Family time', isCritical: false, completed: false },
      { id: 'mon-19', time: '7:00–8:00', description: 'DSA Session 1', isCritical: true, completed: false },
      { id: 'mon-20', time: '8:00–8:15', description: 'Dinner', isCritical: false, completed: false },
      { id: 'mon-21', time: '8:15–10:15', description: 'YouTube', isCritical: false, completed: false },
      { id: 'mon-22', time: '10:15–11:15', description: 'DSA Session 2', isCritical: true, completed: false },
      { id: 'mon-23', time: '11:15–11:25', description: 'Brush + face wash', isCritical: false, completed: false },
      { id: 'mon-24', time: '11:30', description: 'Sleep', isCritical: true, completed: false },
    ],
    notes: '',
  },
  {
    day: 'Tuesday',
    tasks: [
      { id: 'tue-0', time: '11:00 PM (Mon)', description: 'Sleep', isCritical: true, completed: false },
      { id: 'tue-1', time: '6:45', description: 'Wake + water', isCritical: false, completed: false },
      { id: 'tue-2', time: '6:45–6:50', description: 'Toilet', isCritical: false, completed: false },
      { id: 'tue-3', time: '6:50–6:55', description: 'Brush', isCritical: false, completed: false },
      { id: 'tue-4', time: '6:55–7:00', description: 'Face wash', isCritical: false, completed: false },
      { id: 'tue-5', time: '7:00–7:05', description: 'Quick clean', isCritical: false, completed: false },
      { id: 'tue-6', time: '7:05–7:10', description: 'Dress + deodorant', isCritical: false, completed: false },
      { id: 'tue-7', time: '7:10–7:25', description: 'Poha + milk', isCritical: false, completed: false },
      { id: 'tue-8', time: '7:25–7:40', description: 'Revision', isCritical: false, completed: false },
      { id: 'tue-9', time: '7:40–8:00', description: 'Go', isCritical: false, completed: false },
      { id: 'tue-10', time: '8:00–10:00', description: 'Lab', isCritical: true, completed: false },
      { id: 'tue-11', time: '10:00–10:20', description: 'Rest', isCritical: false, completed: false },
      { id: 'tue-12', time: '10:20–10:30', description: 'Wash', isCritical: false, completed: false },
      { id: 'tue-13', time: '10:30–11:00', description: 'Rest', isCritical: false, completed: false },
      { id: 'tue-14', time: '11:00–12:00', description: 'DSA 1', isCritical: true, completed: false },
      { id: 'tue-15', time: '12:30–12:50', description: 'Lunch', isCritical: false, completed: false },
      { id: 'tue-16', time: '1:30–2:30', description: 'Light revision/rest', isCritical: false, completed: false },
      { id: 'tue-17', time: '2:30–5:30', description: 'Classes', isCritical: true, completed: false },
      { id: 'tue-18', time: '5:30–5:45', description: 'Snack', isCritical: false, completed: false },
      { id: 'tue-19', time: '5:45–6:10', description: 'Rest', isCritical: false, completed: false },
      { id: 'tue-20', time: '6:10–6:25', description: 'Walk/run', isCritical: false, completed: false },
      { id: 'tue-21', time: '6:30–7:00', description: 'Family', isCritical: false, completed: false },
      { id: 'tue-22', time: '7:00–8:00', description: 'DSA 2', isCritical: true, completed: false },
      { id: 'tue-23', time: '8:00–8:15', description: 'Dinner', isCritical: false, completed: false },
      { id: 'tue-24', time: '8:15–10:15', description: 'YouTube', isCritical: false, completed: false },
      { id: 'tue-25', time: '10:15–10:25', description: 'Brush + face wash', isCritical: false, completed: false },
      { id: 'tue-26', time: '10:25–12:30', description: 'Free time', isCritical: false, completed: false },
      { id: 'tue-27', time: '12:30–2:00', description: 'Wind down', isCritical: false, completed: false },
      { id: 'tue-28', time: '2:00', description: 'Sleep', isCritical: true, completed: false },
    ],
    notes: '',
  },
  {
    day: 'Wednesday',
    tasks: [
      { id: 'wed-1', time: '8:45', description: 'Wake', isCritical: false, completed: false },
      { id: 'wed-2', time: 'Morning', description: 'Hygiene', isCritical: false, completed: false },
      { id: 'wed-3', time: '9:00–9:20', description: 'Breakfast', isCritical: false, completed: false },
      { id: 'wed-4', time: '9:30–11:00', description: 'DSA Deep', isCritical: true, completed: false },
      { id: 'wed-5', time: '11:00–11:20', description: 'Rest', isCritical: false, completed: false },
      { id: 'wed-6', time: '11:20–11:40', description: 'Bath', isCritical: false, completed: false },
      { id: 'wed-7', time: '11:40–12:30', description: 'Study', isCritical: true, completed: false },
      { id: 'wed-8', time: '12:30', description: 'Lunch', isCritical: false, completed: false },
      { id: 'wed-9', time: '1:00–5:00', description: 'Classes', isCritical: true, completed: false },
      { id: 'wed-10', time: 'Evening', description: 'Snack', isCritical: false, completed: false },
      { id: 'wed-11', time: 'Evening', description: 'Run', isCritical: false, completed: false },
      { id: 'wed-12', time: '6:30–7:00', description: 'Family', isCritical: false, completed: false },
      { id: 'wed-13', time: '7:00–7:45', description: 'DSA 2', isCritical: true, completed: false },
      { id: 'wed-14', time: '7:45', description: 'Dinner', isCritical: false, completed: false },
      { id: 'wed-15', time: '8:00–10:00', description: 'YouTube', isCritical: false, completed: false },
      { id: 'wed-16', time: '10:00–10:45', description: 'Revision', isCritical: false, completed: false },
      { id: 'wed-17', time: 'Night', description: 'Brush', isCritical: false, completed: false },
      { id: 'wed-18', time: '2:00 AM', description: 'Sleep', isCritical: true, completed: false },
    ],
    notes: '',
  },
  {
    day: 'Thursday',
    tasks: [
      { id: 'thu-1', time: '8:45', description: 'Wake', isCritical: false, completed: false },
      { id: 'thu-2', time: 'Morning', description: 'Hygiene', isCritical: false, completed: false },
      { id: 'thu-3', time: '9:10–9:30', description: 'Breakfast', isCritical: false, completed: false },
      { id: 'thu-4', time: '9:30–10:00', description: 'Light DSA', isCritical: true, completed: false },
      { id: 'thu-5', time: '10:00–12:00', description: 'Lab', isCritical: true, completed: false },
      { id: 'thu-6', time: '12:00–12:30', description: 'Reset', isCritical: false, completed: false },
      { id: 'thu-7', time: '12:30', description: 'Lunch', isCritical: false, completed: false },
      { id: 'thu-8', time: '1:30–2:30', description: 'DSA Main', isCritical: true, completed: false },
      { id: 'thu-9', time: '2:30–5:30', description: 'Classes', isCritical: true, completed: false },
      { id: 'thu-10', time: 'Evening', description: 'Snack', isCritical: false, completed: false },
      { id: 'thu-11', time: 'Evening', description: 'Run', isCritical: false, completed: false },
      { id: 'thu-12', time: '6:30–7:00', description: 'Family', isCritical: false, completed: false },
      { id: 'thu-13', time: '7:00–7:30', description: 'DSA Finish', isCritical: true, completed: false },
      { id: 'thu-14', time: 'Night', description: 'Dinner', isCritical: false, completed: false },
      { id: 'thu-15', time: 'Night', description: 'YouTube', isCritical: false, completed: false },
      { id: 'thu-16', time: 'Night', description: 'Hygiene', isCritical: false, completed: false },
      { id: 'thu-17', time: 'Night', description: 'Sleep', isCritical: true, completed: false },
    ],
    notes: '',
  },
  {
    day: 'Friday',
    tasks: [
      { id: 'fri-1', time: '8:45', description: 'Wake', isCritical: false, completed: false },
      { id: 'fri-2', time: 'Morning', description: 'Hygiene', isCritical: false, completed: false },
      { id: 'fri-3', time: '9:00–9:20', description: 'Breakfast', isCritical: false, completed: false },
      { id: 'fri-4', time: '9:30–11:00', description: 'DSA Deep', isCritical: true, completed: false },
      { id: 'fri-5', time: '11:00–11:20', description: 'Rest', isCritical: false, completed: false },
      { id: 'fri-6', time: '11:20–11:40', description: 'Bath', isCritical: false, completed: false },
      { id: 'fri-7', time: '11:40–12:30', description: 'Study', isCritical: true, completed: false },
      { id: 'fri-8', time: '12:30', description: 'Lunch', isCritical: false, completed: false },
      { id: 'fri-9', time: '1:00–5:00', description: 'Classes', isCritical: true, completed: false },
      { id: 'fri-10', time: 'Evening', description: 'Snack', isCritical: false, completed: false },
      { id: 'fri-11', time: 'Evening', description: 'Run', isCritical: false, completed: false },
      { id: 'fri-12', time: '6:30–7:00', description: 'Family', isCritical: false, completed: false },
      { id: 'fri-13', time: '7:00–7:45', description: 'DSA 2', isCritical: true, completed: false },
      { id: 'fri-14', time: '7:45', description: 'Dinner', isCritical: false, completed: false },
      { id: 'fri-15', time: '8:00–10:00', description: 'YouTube', isCritical: false, completed: false },
      { id: 'fri-16', time: '10:00 onwards', description: 'Movie night', isCritical: false, completed: false },
      { id: 'fri-17', time: 'Night', description: 'Brush', isCritical: false, completed: false },
      { id: 'fri-18', time: '2:00 AM', description: 'Sleep', isCritical: true, completed: false },
    ],
    notes: '',
  },
  {
    day: 'Saturday',
    tasks: [
      { id: 'sat-0', time: '1:30–2:00 AM (Fri)', description: 'Sleep', isCritical: true, completed: false },
      { id: 'sat-1', time: '9:00', description: 'Wake + drink water', isCritical: false, completed: false },
      { id: 'sat-2', time: '9:00–9:05', description: 'Toilet', isCritical: false, completed: false },
      { id: 'sat-3', time: '9:05–9:10', description: 'Brush', isCritical: false, completed: false },
      { id: 'sat-4', time: '9:10–9:15', description: 'Face wash', isCritical: false, completed: false },
      { id: 'sat-5', time: '9:15–9:30', description: 'Bath', isCritical: false, completed: false },
      { id: 'sat-6', time: '9:30–9:35', description: 'Dress + deodorant', isCritical: false, completed: false },
      { id: 'sat-7', time: '9:35–9:50', description: 'Breakfast', isCritical: false, completed: false },
      { id: 'sat-8', time: '10:00–11:30', description: 'DSA Session 1', isCritical: true, completed: false },
      { id: 'sat-9', time: '11:30–11:50', description: 'Rest', isCritical: false, completed: false },
      { id: 'sat-10', time: '11:50–12:30', description: 'Study', isCritical: false, completed: false },
      { id: 'sat-11', time: '12:30–12:50', description: 'Lunch', isCritical: false, completed: false },
      { id: 'sat-12', time: '12:50–1:15', description: 'Walk / sit', isCritical: false, completed: false },
      { id: 'sat-13', time: '1:15–2:00', description: 'Rest', isCritical: false, completed: false },
      { id: 'sat-14', time: '2:00–3:00', description: 'DSA Session 2', isCritical: true, completed: false },
      { id: 'sat-15', time: '3:00–4:00', description: 'Light study', isCritical: false, completed: false },
      { id: 'sat-16', time: '4:00–5:00', description: 'Chill', isCritical: false, completed: false },
      { id: 'sat-17', time: '5:00–5:15', description: 'Snack', isCritical: false, completed: false },
      { id: 'sat-18', time: '5:15–5:45', description: 'Rest', isCritical: false, completed: false },
      { id: 'sat-19', time: '5:45–6:05', description: 'Run + stretch', isCritical: false, completed: false },
      { id: 'sat-20', time: '6:30–7:00', description: 'Family time', isCritical: false, completed: false },
      { id: 'sat-21', time: '7:00–7:30', description: 'Light revision', isCritical: false, completed: false },
      { id: 'sat-22', time: '7:45–8:00', description: 'Dinner', isCritical: false, completed: false },
      { id: 'sat-23', time: '8:00–10:00', description: 'YouTube', isCritical: false, completed: false },
      { id: 'sat-24', time: '10:00 onwards', description: 'Movie with friends', isCritical: false, completed: false },
      { id: 'sat-25', time: '1:30–2:00 AM', description: 'Sleep', isCritical: true, completed: false },
    ],
    notes: '',
  },
  {
    day: 'Sunday',
    tasks: [
      { id: 'sun-0', time: '1:30–2:00 AM (Sat)', description: 'Sleep', isCritical: true, completed: false },
      { id: 'sun-1', time: '9:30', description: 'Wake + water', isCritical: false, completed: false },
      { id: 'sun-2', time: '9:30–9:35', description: 'Toilet', isCritical: false, completed: false },
      { id: 'sun-3', time: '9:35–9:40', description: 'Brush', isCritical: false, completed: false },
      { id: 'sun-4', time: '9:40–9:45', description: 'Face wash', isCritical: false, completed: false },
      { id: 'sun-5', time: '9:45–10:00', description: 'Bath', isCritical: false, completed: false },
      { id: 'sun-6', time: '10:00–10:05', description: 'Dress', isCritical: false, completed: false },
      { id: 'sun-7', time: '10:00–10:20', description: 'Breakfast', isCritical: false, completed: false },
      { id: 'sun-8', time: '10:30–11:30', description: 'Lab preparation', isCritical: true, completed: false },
      { id: 'sun-9', time: '11:30–12:00', description: 'Rest', isCritical: false, completed: false },
      { id: 'sun-10', time: '12:00–12:30', description: 'Revision', isCritical: false, completed: false },
      { id: 'sun-11', time: '12:15–12:45', description: 'Lunch', isCritical: false, completed: false },
      { id: 'sun-12', time: '1:00–2:00', description: 'Rest', isCritical: false, completed: false },
      { id: 'sun-13', time: '2:00–3:00', description: 'DSA Session', isCritical: true, completed: false },
      { id: 'sun-14', time: '3:00–4:30', description: 'Light study / chill', isCritical: false, completed: false },
      { id: 'sun-15', time: '5:00–5:15', description: 'Snack', isCritical: false, completed: false },
      { id: 'sun-16', time: '5:30–5:50', description: 'Light run/walk', isCritical: false, completed: false },
      { id: 'sun-17', time: '6:30–7:00', description: 'Family time', isCritical: false, completed: false },
      { id: 'sun-18', time: '7:00–7:30', description: 'Plan next week', isCritical: true, completed: false },
      { id: 'sun-19', time: '7:30', description: 'Check missed tasks', isCritical: false, completed: false },
      { id: 'sun-20', time: '7:45–8:00', description: 'Dinner', isCritical: false, completed: false },
      { id: 'sun-21', time: '8:00–10:00', description: 'YouTube', isCritical: false, completed: false },
      { id: 'sun-22', time: '10:00–10:15', description: 'Brush + face wash', isCritical: false, completed: false },
      { id: 'sun-23', time: '11:30–12:00', description: 'Sleep', isCritical: true, completed: false },
    ],
    notes: '',
  },
];
